name: 非原版 | Not Vanilla
description: 
  表现和原版不同，即使是原版的 bug。
  Behavior is different from vanilla, even if it's a vanilla bug.
labels:
  - "scope: not vanilla"
  - "status: needs triage"
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        在汇报前，请确认您是否使用最新版本的 Leaves
        Before report, please make sure you are using the latest version.<br>
        请详细描述您所遇到的非原版表现。确保您**真的**遇到了 **Leaves 导致的** 与**当前原版版本**不符的特性，而非插件或客户端导致的或是原版版本差异导致的。
        Please describe the non-vanilla behavior you encountered in detail. Make sure you're **actually** hitting a **Leaves-caused** feature that is **different from the current vanilla version**, not caused by plugins or clients or version differences.<br>
        如果您确定的话，就按照下面的模板填充信息，并提交反馈。
        If you are sure, follow the template below to fill in the information and submit your feedback.<br>
        如果这个问题被尝试修复，您可以帮助我们测试并回复。若确认修复，您可以关闭 issue 来告知开发者。
        If this issue is tried to fix, you can help us test and reply. If the issue is fixed, you can close the issue to let the developer confirm.
  - type: input
    id: leaves-version
    attributes:
      label: 服务端版本 Leaves Version
      description:
        Leaves服务端发行版本 Leaves server release version (contains the git commit's hash)<br>
        通过执行`/version`命令将获取到的内容复制到这里。 Run `/version` on your server and paste the full, unmodified output here.
      placeholder: >
        e.g. This server is running Leaves version 1.21.1-79-master@21c276f (2024-11-15T15:39:36Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期的行为 Expected behavior
      description: 你期望看到的情况是什么样。What you expected to see.
      placeholder: e.g. 实体进入传送门传送后动量方向应改变 90°
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 观测到的实际行为 Observed/Actual behavior
      description: 你实际看到的。 What you actually saw.
      placeholder: e.g. 实体进入传送门传送后动量方向改变 45°
    validations:
      required: true  
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤 Steps/models to reproduce
      description:
        这里应该有一个图片、视频或其他信息来展现你的问题。<br>
        This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
      placeholder: 
        e.g. 创建一个传送门，把一个实体推入传送门，观察实体传送后的动量方向。
        image.jpg
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 更多详细信息。 The more information.
