blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/LeavesMC/Leaves/discussions
    about: 对于其它问题 | For other questions
  - name: Discord
    url: https://discord.gg/5hgtU72w33
    about: 在Discord上联系我们 | Contact us on Discord